// Running Examples/vuejs-app/src/components/trucksComponent.vue
<template>
<div class="card-group my-5 py-4">
    <div class="card">
        <img src="https://picsum.photos/id/203/500/550" class="card-img-top">

        <div class="card-body">
            <h5 class="card-title">Card Title</h5>
        </div>

        <ul class="list-group list-group-flush">
            <li class="list-group-item">Hosts</li>
            <li class="list-group-item">Location</li>
            <li class="list-group-item">Date</li>
        </ul>

        <div class="card-body">
            <a href="#" class="card-link">Buy Tickets</a>
            <a href="#" class="card-link">Hosts</a>
        </div>
    </div>

    <div class="card">
        <img src="https://picsum.photos/id/203/500/550" class="card-img-top">

        <div class="card-body">
            <h5 class="card-title">Card Title</h5>
        </div>

        <ul class="list-group list-group-flush">
            <li class="list-group-item">Hosts</li>
            <li class="list-group-item">Location</li>
            <li class="list-group-item">Date</li>
        </ul>

        <div class="card-body">
            <a href="#" class="card-link">Buy Tickets</a>
            <a href="#" class="card-link">Hosts</a>
        </div>
    </div>

    <div class="card">
        <img src="https://picsum.photos/id/203/500/550" class="card-img-top">

        <div class="card-body">
            <h5 class="card-title">Card Title</h5>
        </div>

        <ul class="list-group list-group-flush">
            <li class="list-group-item">Hosts</li>
            <li class="list-group-item">Location</li>
            <li class="list-group-item">Date</li>
        </ul>

        <div class="card-body">
            <a href="#" class="card-link">Buy Tickets</a>
            <a href="#" class="card-link">Hosts</a>
        </div>
    </div>
</div>
</template>

// Running Examples/react-app/src/components/trucksComponent.js
import React from 'react'
import { Card, CardGroup, ListGroup } from 'react-bootstrap';

export const Trucks = () => {
    return (
        <CardGroup className='my-5 py-4'>
        <Card>
          <Card.Img variant="top" src="https://picsum.photos/id/203/500/550" />
          
          <Card.Body>
            <Card.Title>Event Name</Card.Title>
          </Card.Body>

          <ListGroup className="list-group-flush">
            <ListGroup.Item>Hosts</ListGroup.Item>
            <ListGroup.Item>Location</ListGroup.Item>
            <ListGroup.Item>Date</ListGroup.Item>
        </ListGroup>

        <Card.Body>
            <Card.Link>Buy Tickets</Card.Link>
            <Card.Link>Hosts</Card.Link>
        </Card.Body>
        </Card>

        <Card>
          <Card.Img variant="top" src="https://picsum.photos/id/202/500/550" />
          
          <Card.Body>
            <Card.Title>Event Name</Card.Title>
          </Card.Body>

          <ListGroup className="list-group-flush">
            <ListGroup.Item>Hosts</ListGroup.Item>
            <ListGroup.Item>Location</ListGroup.Item>
            <ListGroup.Item>Date</ListGroup.Item>
        </ListGroup>

        <Card.Body>
            <Card.Link>Buy Tickets</Card.Link>
            <Card.Link>Hosts</Card.Link>
        </Card.Body>
        </Card>

        <Card>
          <Card.Img variant="top" src="https://picsum.photos/id/195/500/550" />
          
          <Card.Body>
            <Card.Title>Event Name</Card.Title>
          </Card.Body>

          <ListGroup className="list-group-flush">
            <ListGroup.Item>Hosts</ListGroup.Item>
            <ListGroup.Item>Location</ListGroup.Item>
            <ListGroup.Item>Date</ListGroup.Item>
        </ListGroup>

        <Card.Body>
            <Card.Link>Buy Tickets</Card.Link>
            <Card.Link>Hosts</Card.Link>
        </Card.Body>
        </Card>
      </CardGroup>
    )
}
