// Running Examples/svelte-app/src/App.svelte
<script lang="ts">
  import Router from "svelte-spa-router";
  import "bootstrap/dist/css/bootstrap.min.css";

  import Home from "./routes/Home.svelte";
  import Trucks from "./routes/Trucks.svelte";
  import NotFound from "./routes/NotFound.svelte";

  import Footer from "./components/footer.svelte";

  const routes = {
    "/": Home,
    "/trucks": Trucks,
    "*": NotFound 
  }
</script>

<header>
  <nav class="navbar navbar-dark navbar-expand-lg bg-body-tertiary bg-primary">
    <div class="container">
      <a class="navbar-brand" href="/">MT International</a>
  
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <a class="nav-link" href="#/">Home</a>
          <a class="nav-link" href="#/trucks">Trucks</a>
        </div>
      </div>
    </div>
  </nav>
  </header>

<main class="container">
  <Router {routes}/>
</main>

<Footer/>

// Running Examples/react-app/src/App.js
//Pages
import { Trucks } from './components/trucksComponent';
import { Home } from './components/homeComponent';

//Router
import { BrowserRouter, Routes, Route, Link } from "react-router-dom";

//Navigation Bar
import { Container, Nav, Navbar } from 'react-bootstrap';

//UI Components
import {  } from 'react-bootstrap';

//App Function
function App() {
  return (
    <BrowserRouter>
      <div>
        <header>
          <>
          <Navbar bg="primary" variant="dark">
            <Container>
              <Navbar.Brand as={Link} to="/">MT International</Navbar.Brand>
              <Nav className="me-auto">
                <Nav.Link as={Link} to="/">Home</Nav.Link>
                <Nav.Link as={Link} to="/trucks">Trucks</Nav.Link>
              </Nav>
            </Container>
          </Navbar>
          </>
        </header>

        <main className='container'>
            <Routes>
              <Route path='/' element={<Home/>}/>
              <Route path='/trucks' element={<Trucks/>}/>
            </Routes>
        </main>

        <footer className='pt-3 pb-1 bg-primary mt-5'>
          <Container>
            <p className='text-center text-white'>Copyright &copy; Codie Shannon 2023</p>
          </Container>
        </footer>
      </div>
    </BrowserRouter>
  );
}

//Export App Function
export default App;
